name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore      
    - name: Unit Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish AnimalAdoption.Web.Portal --configuration Release --no-restore --output publish/web-portal
    - name: Package
      run: dotnet pack --configuration Release AnimalAdoption.Common.Logic --output publish/common-logic
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: web-portal
        path: publish/web-portal
        if-no-files-found: error
    - name: Upload Package
      uses: actions/upload-artifact@v2.1.4
      with:
        name: nuget-lib
        path: publish/common-logic
        if-no-files-found: error

  test_deployment:
    runs-on: ubuntu-latest    
    needs: [build]
    env:
      TEST_RESOURCE_GROUP_NAME: ss-gh-devops-simon
      TEST_APP_SERVICE_PLAN_NAME: ASP-sprintseriesghdevopssimon-87e7
      TEST_KEY_VAULT_NAME: ss-gh-devops-simon2
      TEST_WEB_APP_NAME: ss-gh-devops-simon
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy resources to the Test Resource Group using an ARM template
      uses: whiteducksoftware/azure-arm-action@v3.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resourceGroupName: ${{ env.TEST_RESOURCE_GROUP_NAME }}
        templateLocation: ./deploy.json
        deploymentName: gha-test-deploy
        deploymentMode: Incremental
        overrideParameters: |
          resourceLocation=australiasoutheast
          tenantGuid=dab167d2-fdab-4ab5-a387-22f955436d0a
          appServicePlanName=${{ env.TEST_APP_SERVICE_PLAN_NAME }}
          keyVaultName=${{ env.TEST_KEY_VAULT_NAME }}
          webAppName=${{ env.TEST_WEB_APP_NAME }}
          resourceGroupServicePrincipalManagedApplicationObjectId=05c9c9da-cf96-4f1a-879e-e2b30419b8d8
    - name: Download web-portal
      uses: actions/download-artifact@v2
      with:
        name: web-portal
        path: deps/web-portal
    - name: Deploy test web-portal
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ss-gh-devops-simon
        package: .
    - name: Get key vault secret
      uses: Azure/get-keyvault-secrets@v1
      id: global-password-secret
      with:
        keyvault: ss-gh-devops-simon2
        secrets: 'GlobalPassword, SimulatedFailureChance'
    - name: Configure test web-portal
      uses: Azure/appservice-settings@v1
      with:
        app-name: ss-gh-devops-simon
        app-settings-json: | 
          [ 
            {
              "name": "GlobalPassword",
              "value": "${{ env.GlobalPassword }}",
              "slotSetting": false
            },
            {
              "name": "SimulatedFailureChance",
              "value": "${{ env.SimulatedFailureChance }}"",
              "slotSetting": false
            }
          ]
  nuget:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download common-logic
      uses: actions/download-artifact@v2
      with:
        name: nuget-lib
    - name: Add NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/Simon-Campbell/index.json -n github -u Simon-Campbell -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Publish NuGet Package
      run: dotnet nuget push "*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate