name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore      
    - name: Unit Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish AnimalAdoption.Web.Portal --configuration Release --no-restore --output publish/web-portal
    - name: Package
      run: dotnet pack --configuration Release AnimalAdoption.Common.Logic --output publish/common-logic
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: web-portal
        path: publish/web-portal
        if-no-files-found: error
    - name: Upload Package
      uses: actions/upload-artifact@v2.1.4
      with:
        name: nuget-lib
        path: publish/common-logic
        if-no-files-found: error

  deployment:
    runs-on: ubuntu-latest    
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI Action
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: | 
          az deployment group create \
          --resource-group sprintseries-gh-devops-simon \
          --template-file ./deploy.json \
          --parameters resourceLocation=australiasoutheast tenantGuid=dab167d2-fdab-4ab5-a387-22f955436d0a appServicePlanName=ASP-sprintseriesghdevopssimon-87e7 keyVaultName=ss-gh-devops-simon webAppName=sprintseries-gh-devops-simon resourceGroupServicePrincipalManagedApplicationObjectId=45c5014c-69e4-4726-bdc4-a490145f7f56 keyVaultSecretValueGlobalPassword=k3yv4ult keyVaultSecretValueSimulatedFailureChance=2
    - name: Download web-portal
      uses: actions/download-artifact@v2
      with:
        name: web-portal
        path: deps/web-portal
    - name: Deploy test web-portal
      uses: Azure/webapps-deploy@v2
      with:
        app-name: sprintseries-gh-devops-simon
        package: .
    - name: Get key vault secret
      uses: Azure/get-keyvault-secrets@v1
      id: global-password-secret
      with:
        keyvault: ss-gh-devops-simon
        secrets: GlobalPassword
    - name: Configure test web-portal
      uses: Azure/appservice-settings@v1
      with:
        app-name: sprintseries-gh-devops-simon
        app-settings-json: | 
          [ 
            {
              "name": "GlobalPassword",
              "value": "${{ env.GlobalPassword }}",
              "slotSetting": false
            },
            {
              "name": "SimulatedFailureChance",
              "value": 2,
              "slotSetting": false
            }
          ]
  nuget:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download common-logic
      uses: actions/download-artifact@v2
      with:
        name: nuget-lib
    - name: Add NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/Simon-Campbell/index.json -n github -u Simon-Campbell -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Publish NuGet Package
      run: dotnet nuget push "*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate