name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore      
    - name: Unit Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish AnimalAdoption.Web.Portal --configuration Release --no-restore --output publish/web-portal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: web-portal
        path: publish/web-portal
        if-no-files-found: error
  deployment:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download web-portal
      uses: actions/download-artifact@v2
      with:
        name: web-portal
    - name: Deploy test web-portal
      uses: Azure/webapps-deploy@v2
      with:
        app-name: sprintseries-gh-devops-simon
        publish-profile: ${{ secrets.PORTAL_PUBLISH_PROFILE }}    
        package: .
  nuget:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Add NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/Simon-Campbell/index.json -n github -u Simon-Campbell -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Package
      run: dotnet pack --configuration Release AnimalAdoption.Common.Logic --output publish/common-logic
    - name: Publish NuGet Package
      run: dotnet nuget push "publish/common-logic/*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
